import type { Metadata } from "next";
import Navbar from "@/components/navbar/page";
import Footer from "@/components/footer/page";
import "./globals.css";

// Optional: You can import Google Fonts if needed
// import { Geist, Geist_Mono } from "next/font/google";

export const metadata: Metadata = {
  title: "SkillWrap",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-white text-black">
        {/* Navbar */}
        <Navbar />

        {/* Main content */}
        <main>{children}</main>

        {/* Footer */}
        {/* <Footer /> */}
      </body>
    </html>
  );
}

