import type { Metadata } from "next";
import Navbar from "@/components/navbar/page";
import Footer from "@/components/footer/page";
import "./globals.css";

export const metadata: Metadata = {
  title: {
    default: "SkillWrap",
    template: "%s | SkillWrap",
  },
  description:
    "SkillWrap is a modern skill-sharing platform where learners, mentors, and creators connect through teaching, learning, events, challenges, and skill exchanges.",
  keywords: [
    "SkillWrap",
    "Learning",
    "Teaching",
    "Skill Sharing",
    "Mentorship",
    "Education",
    "Community",
    "Events",
    "Challenges",
    "Exchange",
  ],
  authors: [{ name: "SkillWrap Team" }],
  creator: "SkillWrap",
  publisher: "SkillWrap",

  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },

  openGraph: {
    title: "SkillWrap",
    description:
      "Learn, Teach, Exchange Skills, Join Challenges and Grow Together.",
    siteName: "SkillWrap",
    type: "website",
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 630,
        alt: "SkillWrap",
      },
    ],
  },

  twitter: {
    card: "summary_large_image",
    title: "SkillWrap",
    description:
      "Learn, Teach, Exchange Skills, Join Challenges and Grow Together.",
    images: ["/og-image.png"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen bg-slate-950 text-white antialiased">
        <div className="flex min-h-screen flex-col">
          {/* Global Navbar */}
          <Navbar />

          {/* Main Content */}
          <main className="flex-1">{children}</main>

          {/* Global Footer */}
          <Footer />
        </div>
      </body>
    </html>
  );
}


// import type { Metadata } from "next";
// import Navbar from "@/components/navbar/page";
// import Footer from "@/components/footer/page";
// import "./globals.css";

// // Optional: You can import Google Fonts if needed
// // import { Geist, Geist_Mono } from "next/font/google";

// // export const metadata: Metadata = {
// //   title: "SkillWrap",
// //   description: "Generated by create next app",
// // };

// export const metadata: Metadata = {
//   title: "SkillWrap",
//   description: "Generated by create next app",
//   icons: {
//     icon: "/favicon.ico",
//     shortcut: "/favicon.ico",
//     apple: "/apple-touch-icon.png",
//   },
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className="bg-white text-black">
//         {/* Navbar */}
//         <Navbar />

//         {/* Main content */}
//         <main>{children}</main>

//         {/* Footer */}
//         <Footer />
//       </body>
//     </html>
//   );
// }

